version: '3.8'
services:
  pythontelegrambottemplate:
    #image: ghcr.io/<fcklck>/<FRANGU96_prjct_URFU>
    image: pythontelegrambottemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: "${TZ}"
      BOT_TOKEN: "${BOT_TOKEN}"
      PYTHONPATH: "${PYTHONPATH}"
    volumes:
      - ./data:/app/data  
    restart: unless-stopped
